### PR TITLE
fix: update node-yaml-config to 0.0.6 version

### PR DESCRIPTION
**Pull request by aayushmau5**
**Description**
Updated `node-yaml-config` to version 0.0.6 as 0.0.4 was giving "high severity" error.

**Related issue(s)**

### CODE REVIEW

**Review by derberg — CHANGES_REQUESTED** [review]
this part is strange 
https://github.com/asyncapi/nodejs-ws-template/pull/75/files#diff-acf6842e8274b8473242ea8bc426979f4aab613c4abc50990902d35f598bd58bR7-R16

there are lots of changes there in package-lock, I think better will be to only update the package.json. Sorry for additional work

**Comment by aayushmau5** [comment]
Had to force push :sweat_smile: , but It's done.

**Review by derberg — APPROVED** [review]
Thanks so much!

**Comment by derberg** [comment]
@all-contributors please add @aayushmau5 for security

**Pull request merged**
