### PR TITLE
fix: update template to work with @asyncapi/parser 2.x

### LINKED ISSUE #271: Template incorrectly references 2.x versions of @asyncapi/parser instead of 1.x
#### Describe the bug

When creating a new project using this template, the `@asyncapi/parser` version is `"^2.0.0-next-major.15"`. It appears that there are breaking changes in this version when coming from `1.x`. Because of these changes, the following errors is thrown when trying to run the generated application out-the-box (after running `npm install`):

```
(node:10540) UnhandledPromiseRejectionWarning: TypeError: parse is not a function
    at Object.module.exports.init (D:\Code\AsyncApiFoodDelivery\ws-server\src\lib\asyncapi.js:23:20)
    at start (D:\Code\AsyncApiFoodDelivery\ws-server\src\api\index.js:9:18)
    at Object.<anonymous> (D:\Code\AsyncApiFoodDelivery\ws-server\src\api\index.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

After some testing, I noticed that the `parse` method is present in `1.x` versions of the `@asyncapi/parser` package. When updating my `package.json` file to reference `"^1.18.1"` the application works.

We can fix this by either:

- Updating the `package.json` file in the template to reference `"^1.18.1"` OR
- Rewrite the template to be compatible with the `2.x` version of the `@asyncapi/parser`. Will this be a big change? Should we do this if `2.x` isn't released yet?

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

1. Generate a project using the template: `ag asyncapi.yaml @asyncapi/nodejs-ws-template -p server=dev -o ws-server`
2. Install NPM packages: `npm install`
3. Run the application: `npm run start`

#### Expected behaviour

The application should start successfully and let me connect to the WebSocket paths.

### PR DESCRIPTION
**Pull request by ivankahl**
**Description**

- Updated the https://github.com/ivankahl/nodejs-ws-template/blob/master/template/src/lib/asyncapi.js file to use the new Parser API in 2.x

**Tests**

I updated the test snapshot as the template change. See integration test results below:

```
 PASS  test/integration.test.js
  template integration test using generator
    ✓ should generate application files  (660 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   6 passed, 6 total
Time:        3.067 s
Ran all test suites.
```

I tested the template by using it for my own project and checking the application runs and the WebSocket works. Please see test results below:

```
D:\Code\AsyncApiFoodDelivery
❯ ag asyncapi.yaml https://github.com/ivankahl/nodejs-ws-template -p server=dev -o ws-server --force-write


Done! ✨
Check out your shiny new generated files at D:\Code\AsyncApiFoodDelivery\ws-server.


D:\Code\AsyncApiFoodDelivery took 36s
❯ cd .\ws-server\

Code\AsyncApiFoodDelivery\ws-server is 📦 v1.0.0 via  v14.21.3 
❯ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN food-delivery-api@1.0.0 No repository field.
npm WARN food-delivery-api@1.0.0 No license field.

added 190 packages from 175 contributors and audited 190 packages in 19.415s

45 packages are looking for funding
  run `npm fund` for details

found 3 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

Code\AsyncApiFoodDelivery\ws-server is 📦 v1.0.0 via  v14.21.3 took 21s
❯ npm run start

> food-delivery-api@1.0.0 start D:\Code\AsyncApiFoodDelivery\ws-server
> node src/api/index.js

Listening on port 3000
```

Proof that the WebSocket connection works:
image

**Related issue(s)**
Resolves #271

### CODE REVIEW

**Comment by derberg** [comment]
@ivankahl I update PR title (must start lower case). Please update snapshots for tests, as template code changed

**Comment by ivankahl** [comment]
Sure thing @derberg, I've updated the snapshot and the tests pass:

```
 PASS  test/integration.test.js
  template integration test using generator
    ✓ should generate application files  (660 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   6 passed, 6 total
Time:        3.067 s
Ran all test suites.
```

**Review by derberg — APPROVED** [review]
Thanks

**Comment by derberg** [comment]
@allcontributors please add @ivankahl for code, test

**Pull request merged**
